### PR TITLE
sum string projection as integer of bool

### PR DESCRIPTION
**Pull request by rks0nax**
# Description of change

Fixes issue - #93
The change allows user to specify string projection, instead of just integer values 

A sample projection that didn't work before and should be working after merging this PR
`{"name": "$personName"}`

# QA steps
 - [ ] automated tests passing
 - [x] manual qa steps passing (list below)
 
# Risks

# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by dmcquay** [comment]
I need this fix badly. Looks like this has been ready to merge for a long time. What's the hold up?
@rks0nax Thanks for reporting and contributing the fix! Was very happy to see this.

**Comment by dmcquay** [comment]
@cosimon can you provide an update on this?

**Comment by dmcquay** [comment]
In the Stitch troubleshooting documentation, their recommended course of action for column or table name too long loading errors is to omit the table from the source, rename at the source or switch to a different destination.
https://www.stitchdata.com/docs/troubleshooting/destinations/destination-loading-error-reference#column-name-limit

This PR would allow us to instead use aliases in mongo projections to address the issue.

**Comment by dmcquay** [comment]
And please notice that the change is:
1. Only one line
2. Seems to me like disallowing string values here was an accident in the first place, not strategic. So this really just feels like a bug fix.

Seems like it is a no brainer to get this merged.

**Review by rdeshmukh15 — APPROVED** [review]

**Pull request merged**
